version: '3.8'

services:
  victoria-metrics:
    image: victoriametrics/victoria-metrics
    container_name: victoria-metrics
    ports:
      - "8428:8428" # Expose the default port
    volumes:
      - ./victoria-metrics-data:/victoria-metrics-data # Persistent storage for data
    restart: always
    